name: Database migrations

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  migrations:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: automation
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d automation" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/automation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Apply database migrations
        run: npm run db:push

      - name: Seed encryption key
        run: npm run seed:encryption-key
        env:
          ENCRYPTION_MASTER_KEY: local-development-master-key-please-rotate
          DEFAULT_ENCRYPTION_KEY_ID: ci/local-dev
          DEFAULT_ENCRYPTION_KEY_ALIAS: CI default key
